#!/usr/bin/env python3
"""Emit reports/model_card.md from training and ablation JSON artifacts (no hand-fabricated metrics).

Reads:
  --training-meta   (default: outputs/preference_lora/training_meta.json)
  --ablation        (default: reports/ablation_results.json)
  --metrics-jsonl   (optional: reports/training_run_metrics.jsonl; last N lines summarized)

Usage:
  uv run python scripts/emit_model_card.py \\
    --training-meta outputs/preference_lora_run1/training_meta.json \\
    --adapter outputs/preference_lora_run1/lora_adapter
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]


def _read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _tail_metrics(path: Path, n: int) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    lines = path.read_text(encoding="utf-8").strip().splitlines()
    out: List[Dict[str, Any]] = []
    for line in lines[-n:]:
        line = line.strip()
        if line:
            out.append(json.loads(line))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate model_card.md from run artifacts.")
    ap.add_argument(
        "--training-meta",
        type=Path,
        default=REPO_ROOT / "outputs" / "preference_lora" / "training_meta.json",
    )
    ap.add_argument("--adapter", type=Path, default=REPO_ROOT / "outputs" / "preference_lora" / "lora_adapter")
    ap.add_argument(
        "--ablation",
        type=Path,
        default=REPO_ROOT / "reports" / "ablation_results.json",
    )
    ap.add_argument(
        "--metrics-jsonl",
        type=Path,
        default=REPO_ROOT / "reports" / "training_run_metrics.jsonl",
    )
    ap.add_argument("--metrics-tail", type=int, default=15)
    ap.add_argument(
        "--author",
        type=str,
        default="Hiwot Beyene",
        help="Name shown under Author / maintainer on the model card.",
    )
    ap.add_argument(
        "--hf-handle",
        type=str,
        default="hiwot-beyene",
        help="Hugging Face username for optional profile link (empty string to omit link).",
    )
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "reports" / "model_card.md")
    args = ap.parse_args()

    if not args.training_meta.exists():
        raise SystemExit(f"missing {args.training_meta}; run training/preference_lora_train.py first")

    meta = _read_json(args.training_meta)
    abl: Optional[Dict[str, Any]] = None
    if args.ablation.exists():
        abl = _read_json(args.ablation)
    metrics_tail = _tail_metrics(args.metrics_jsonl, args.metrics_tail)

    author_lines = [
        "## Author / maintainer",
        "",
        f"- **{args.author}** — Path B preference LoRA (Tenacious-Bench Week 11).",
    ]
    if args.hf_handle.strip():
        author_lines.append(
            f"- Hugging Face: [`{args.hf_handle}`](https://huggingface.co/{args.hf_handle})."
        )
    author_lines.append("")

    lines: List[str] = [
        "# Model card",
        "",
        "This file is generated by `scripts/emit_model_card.py` from committed run artifacts.",
        "",
        *author_lines,
        "## Base model",
        "",
        f"- **Hub id:** `{meta.get('model_id', '')}`",
        f"- **Hub revision (pinned):** `{meta.get('model_revision_hf')}`",
        f"- **Adapter path (PEFT):** `{args.adapter}`",
        "",
        "## Training",
        "",
        "- **Path B — Objective:** DPO (TRL `DPOTrainer`) with LoRA only (`finetuning_mode` in meta).",
        f"- **Seed:** {meta.get('seed')}",
        f"- **Beta:** {meta.get('dpo_beta')}",
        f"- **LoRA r / alpha / dropout:** {meta.get('lora_r')} / {meta.get('lora_alpha')} / {meta.get('lora_dropout')}",
        f"- **LR scheduler / warmup:** {meta.get('lr_scheduler_type')} / steps={meta.get('warmup_steps')} ratio={meta.get('warmup_ratio')}",
        f"- **Train file:** `{meta.get('train_jsonl')}`",
        f"- **Validation file:** `{meta.get('valid_jsonl')}`",
        f"- **Epochs / max steps:** {meta.get('num_train_epochs')} / {meta.get('max_steps')}",
        f"- **Batch train / eval (per device) / grad accumulation:** {meta.get('per_device_train_batch_size')} / {meta.get('per_device_eval_batch_size')} / {meta.get('gradient_accumulation_steps')}",
        f"- **Learning rate:** {meta.get('learning_rate')}",
        f"- **Target modules:** {', '.join(meta.get('target_modules') or [])}",
        "",
        "## Training metrics (recent log events)",
        "",
        "```json",
        json.dumps(metrics_tail, indent=2),
        "```",
        "",
    ]

    if abl:
        lines.extend(
            [
                "## Held-out evaluation (Tenacious-Bench sealed slice)",
                "",
                "```json",
                json.dumps(
                    {
                        "n_pairs": abl.get("n_pairs") or abl.get("n_pairs_input"),
                        "comparisons_run": abl.get("comparisons_run"),
                        "accuracies": abl.get("accuracies"),
                        "delta_a_trained_vs_baseline": abl.get("delta_a_trained_vs_baseline"),
                        "delta_b_trained_vs_prompt_only": abl.get("delta_b_trained_vs_prompt_only"),
                        "delta_c_tau2_retail": abl.get("delta_c_tau2_retail"),
                        "cost_pareto": abl.get("cost_pareto"),
                    },
                    indent=2,
                ),
                "```",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Held-out evaluation",
                "",
                "_No `reports/ablation_results.json` found; run `scripts/run_sealed_ablation.py` after training._",
                "",
            ]
        )

    lines.extend(
        [
            "## Intended use",
            "",
            "Preference-tuned adapter for Path B: improve alignment with Tenacious-Bench pairwise preferences ",
            "under the pinned instruct backbone. Not a general-purpose chat model replacement.",
            "",
            "## Limitations",
            "",
            "- Metrics above are slice-specific; τ²-Bench retail is out of scope for this week unless you paste a stored score into ablation JSON.",
            "- Log-prob preference accuracy is a proxy; task-level agent success may differ.",
            "",
        ]
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"wrote": str(args.out)}, indent=2))


if __name__ == "__main__":
    main()
